export * as loginApi from './login';
export * as clientApi from './client';
export * as accountApi from './account';
export * as interfaceApi from './interface';
export * as consumeApi from './consume';

// export * as searchApi from './search';
// export * as reportListApi from './reportList';
// export * as analysisListApi from './analysisList';
// export * as monitorListApi from './monitorList';
// export * as companyHomeApi from './companyHome';
// export * as myHomePageApi from './myHomePage';
// export * as riskHeadlinesApi from './riskHeadline';
// export * as addRelationApi from './addRelation';
// export * as accountSettingApi from './accountSetting';
// export * as monitorStatisticsApi from './monitorStatistics';
// export * as ruleApi from './rule';
// export * as personReportApi from './personReport';
// export * as collectionApi from './collection';
// export * as ruleCompanyApi from './ruleCompany';
// export * as bidMarketApi from './bidMarket';
// export * as highRiskCorpApi from './highRiskCorp';
// export * as accountProfileApi from './accountProfile';
// export * as assetTransactionApi from './assetTransaction';
// export * as linkJumpApi from './linkJump';
// export * as relPerCheckApi from './relPerCheck';
// export * as pdfApi from './pdf';
// export * as moduleInfoApi from './moduleInfo';
// export * as blackListScanApi from './blackListScan';
// append here from plop
